# Generated by Django 4.0 on 2023-04-20 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HallDetails',
            fields=[
                ('hallname', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('guests', models.IntegerField(default=' ')),
                ('halltype', models.CharField(max_length=200)),
                ('hall_image', models.ImageField(blank=True, default='', null=True, upload_to='TheEventJoy/Images')),
            ],
        ),
        migrations.CreateModel(
            name='HallSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeslot', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DetailFood',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=100)),
                ('fprice', models.IntegerField(default=' ')),
                ('fcategory', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='TheEventJoyApp.categoryfood')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timeslot', models.CharField(max_length=100)),
                ('bill', models.IntegerField(default=' ')),
                ('items_json', models.CharField(default='', max_length=10000)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('booked_hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TheEventJoyApp.halldetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
