# Generated by Django 4.0 on 2023-04-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheEventJoyApp', '0002_alter_booking_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_hall',
            field=models.CharField(max_length=200),
        ),
    ]
