# Generated by Django 4.0 on 2023-04-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheEventJoyApp', '0005_usersession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='hall_date',
        ),
        migrations.AlterField(
            model_name='booking',
            name='bill',
            field=models.CharField(max_length=500),
        ),
    ]
