# Generated by Django 4.0 on 2023-05-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheEventJoyApp', '0008_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailfood',
            name='fid',
        ),
        migrations.AlterField(
            model_name='detailfood',
            name='fname',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
