# Generated by Django 4.0 on 2023-11-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheEventJoyApp', '0009_remove_detailfood_fid_alter_detailfood_fname'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailfood',
            name='fid',
            field=models.AutoField(default=' ', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detailfood',
            name='fname',
            field=models.CharField(max_length=100),
        ),
    ]
