# Generated by Django 5.0.4 on 2024-05-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheEventJoyApp', '0010_detailfood_fid_alter_detailfood_fname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailfood',
            name='fid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
